# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
jobs:
  welcome/run:
    docker:
    - image: circleci/welcome-config-image:0.1.40-b28e6fe
    steps:
    - run:
        command: welcome_message.sh
        name: Welcome and basics to get you started
    - run:
        command: common_env_vars.sh
        name: Built-in environment variables for your project
    - run:
        command: next_steps.sh
        name: Next steps to customize your pipeline

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  # Name the workflow "Welcome"
  Welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run:
          filters:
            tags:
              only: /.*/

