# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    machine: true
    steps:
      - run: echo build job
  test:
    machine: true
    steps:
      - run: echo test job
  deploy:
    machine: true
    steps:
      - run: echo deploy
      - run:
          name: Whether exists tag
          command: |
            if [ "${CIRCLE_TAG-undefined}" != "undefined" ]; then
                echo exist ^v.* tag
            else
                echo no tag
            fi

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  build-test-and-deploy:
    jobs:
      # build and test jobs is all branch
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - deploy2:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/

